### ISSUE TITLE
Create skeleton of TestNG based test suite

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-cat20-dgiwg10#1]

**Comment by dstenger** [comment]
CITE Maven archetype [1] is used for generation of first structure:

```
mvn archetype:generate -B \
    -DarchetypeGroupId=org.opengis.cite \
    -DarchetypeArtifactId=ets-archetype-testng \
    -DarchetypeVersion=2.7-SNAPSHOT \
    -Dets-code=cat20-dgiwg10 \
    -DartifactId=ets-cat20-dgiwg10 \
    -Dpackage=org.opengis.cite.cat20.dgiwg10
```

Create initial commit:

```
git init
git add .
git commit -m"Create skeleton of TestNG based test suite with CITE Maven archetype"
git remote add origin git@github.com:opengeospatial/ets-cat20-dgiwg10.git
git push -u origin master
```

Commit: https://github.com/opengeospatial/ets-cat20-dgiwg10/commit/aa9ff38a64e98faae37525c8b09ea2408c2a5317

[1] https://github.com/opengeospatial/ets-archetype-testng

**Comment by dstenger** [comment]
## Further adjustments

Add gitignore: https://github.com/opengeospatial/ets-cat20-dgiwg10/commit/dda8d8e92c994faee9ab07b10fdc3b2769940369
Update ets-common version: https://github.com/opengeospatial/ets-cat20-dgiwg10/commit/d75c9dbbe63c6ff03a178b0f239a0b56dfa8e5cb
Remove method assertSchematronValid (because of compiler errors after update of ets-common): https://github.com/opengeospatial/ets-cat20-dgiwg10/commit/414b089ab03c681ff68333130b1c42b6757b7c39
Move resources to correct package and update paths: https://github.com/opengeospatial/ets-cat20-dgiwg10/commit/286fb60072f351f58e113069c8d71557499577f1

**Comment by lgoltz** [comment]
Skeleton of the test suite was created. `mvn clean install` was successful.
