### ISSUE TITLE
Verify compliance with the DMF specification (Requirement 11)

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-cat20-dgiwg10#14]
A.1.2 (#5) and A.1.3 (#6) has a test method

```
Verify that the gmd:MD_Metadata record returned is compliant with the DMF
specification (Requirement 11) and with ISO19139 (Requirement 12). Returnables
shall be mapped to the DMF using table 5,6,8,9 and 10 (Requirement 10)
```

This is currently not implemented. How can we test this?

**Comment by cmheazel** [comment]
I checked with the U.S. folks who participate in DGIWG and there does not appear to be a validation test for DMF documents.  The compliance portion of the DMF is primarily focused on the creation of DMF catalogs and profiles.  There is a section on Metadata Set validation, but no specific instructions on how this validation should take place.  So I suggest that for TB-14 we only perform the validations that DGIWG provides and leave the rest as future work.  Content which can be used for a Future Work entry is attached

[DMF compliance Future Work.docx](https://github.com/opengeospatial/ets-cat20-dgiwg10/files/2283862/DMF.compliance.Future.Work.docx)

**Comment by dstenger** [comment]
Thus, in respect to the test suite developed during Testbed 14, we conclude that we do a schema validation against schema of chapter C.3 of ```DGIWG 114 - DGIWG Metadata Foundation``` [1].

@cmheazel Do you agree to this solution?

[1] https://portal.dgiwg.org/files/?artifact_id=67565

**Comment by cmheazel** [comment]
@dstenger  Close.  I'll send you the XML schemas I have.  They should be the authoritative ones, but I'll double check.
