### ISSUE TITLE
Improve test GetCapabilities.verifyGetRecordsQueryables()

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-cat20-dgiwg10#21]
SUT: http://dgiwg.geo-solutions.it/geonetwork/srv/eng/csw?REQUEST=GetCapabilities&SERVICE=CSW

Test GetCapabilities.verifyGetRecordsQueryables() fails with 
`Missing queryables for GetRecords operation: [BoundingBox, Source, Association, CRS] `

**Comment by lgoltz** [comment]
## BoundingBox
Is a compound element with the following compositions (CSW 2.0.2 and ISO AP):
 * WestBoundLongitude
 * SouthBoundLatitude
 * EastBoundLongitude
 * NorthBoundLatitude

## Source
Is part of the compound element  `Association` (below).

## Association
Queryable `Association` is defined as "The name of the relationship that exists between the resource described by this record and a related resource referenced using the Source or dc:source property." (CSW 2.0.2 and DGIWG).

Is described in CSW 2.0.2 as a compound element with the following compositions:
 * Target
 * Source
 * Relation

ISO AP does not define a mapping for this queryable (Table 6).
In DGIWG a Corresponding DMF element  is not supported.

The SUT specifies  `Relation` as queryable.

## CRS
Specified in CSW 2.0.2. In ISO AP as compound element with the following compositions:
 * Authority
 * ID
 * Version

**Comment by lgoltz** [comment]
Proposal:
Remove expected queryables `BoundingBox`, `CRS` and replace them with the compositions. Clarify if `Association` is expected from DGIWG.

**Comment by etj** [comment]
Please note the queriables `Source` and `Association` are marked as "not supported" DMF elements in the last column of table 5, so they may be not needed.

**Comment by etj** [comment]
I added the BoundingBox in the getCapabilities, since it's queriable in the spatial filters;
e.g.
```
<?xml version="1.0"?>

<csw:GetRecords 
         xmlns:csw="http://www.opengis.net/cat/csw/2.0.2"
         service="CSW" 
         version="2.0.2">
   <csw:Query typeNames="csw:Record">
      <csw:Constraint version="1.1.0">
         <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc">
            <ogc:BBOX>
               <ogc:PropertyName>iso:BoundingBox</ogc:PropertyName>
               <gml:Envelope xmlns:gml="http://www.opengis.net/gml">
                  <gml:lowerCorner>-20 -20</gml:lowerCorner>
                  <gml:upperCorner>20 20</gml:upperCorner>
               </gml:Envelope>
            </ogc:BBOX>
         </ogc:Filter>
      </csw:Constraint>
   </csw:Query>
</csw:GetRecords>
```

**Comment by etj** [comment]
I would leave the requirements for having "CRS" and "BoundingBox" in the getCapabilities.
The CRS should be encoded as a URI, as per DMF recommendation.
About CRS, the "Authority", "ID" and "Version" field names are quite ambiguous when used without a parent concept, while the URI encoding would be fine for both querying and as returned value.
About BoundingBox, the extent coordinates are seldom used on their own, and the bbox is used as a whole in spatial filtering.

**Comment by lgoltz** [comment]
> The CRS should be encoded as a URI, as per DMF recommendation.
> About CRS, the "Authority", "ID" and "Version" field names are quite ambiguous when used without a parent concept, while the URI encoding would be fine for both querying and as returned value.

As CRS is mapped to RSRSYS.code (a simple text field or anchor as described in https://portal.dgiwg.org/files/?artifact_id=67565, 5.4.2.20 Identifier) and CSW 2.0.2 does not specify this queryable as compound element I agree with you that we should keep "CRS" and remove  "Authority", "ID" and "Version" (furthermore "Version" has no mapping).

> About BoundingBox, the extent coordinates are seldom used on their own, and the bbox is used as a whole in spatial filtering.

I agree with you in this point. But is this expected by he specification?

**Comment by lgoltz** [comment]
We decided to use CRS and BoundingBox instead of the  "Authority", "ID", "Version" and "WestBoundLongitude", "SouthBoundLatitude", "EastBoundLongitude", "NorthBoundLatitude".
