### ISSUE TITLE
Req19 overrides req4

### ISSUE THREAD

**Issue by etj** [opengeospatial/ets-cat20-dgiwg10#24]
The abstract snippet required by req4 is replaced by req19.
The test should allow either text.

```
<test-method 
   status="FAIL" 
   signature="verifyMetadataLink()[pri:0, instance:org.opengis.cite.cat20.dgiwg10.getcapabilities.GetCapabilities@9dc26a]" 
   name="verifyMetadataLink" 
   duration-ms="2" started-at="2018-08-28T12:53:36Z" 
   description="Implements A.1.1 GetCapabilities for DGIWG Basic CSW (Requirement 4)" 
   depends-on-methods="org.opengis.cite.cat20.dgiwg10.getcapabilities.GetCapabilities.verifyNoError" 
   finished-at="2018-08-28T12:53:36Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Abstract does not contain the expected text 'This service implements the DGIWG Catalogue Service for the Web ISO Profile version 1.0, DGIWG Basic CSW conformance class (http://www.dgiwg.org/std/csw/1.0/conf/basic)'. expected [true] but found [false]]]>
            </message>
  [...]
```

**Comment by lgoltz** [comment]
Requirement 19 will be tested in A.1.4 DGIWG Transactional CSW which is not implemented yet (#7).

**Comment by etj** [comment]
Well, ok, but the related test will be reporting a false failure, since the catalog is following req19 and not req4.

**Comment by lgoltz** [comment]
The text from Requirement 19 includes the one from Requirement 4:
 * Requirement 4: `This service implements the DGIWG Catalogue Service for the Web ISO Profile version 1.0, DGIWG Basic CSW conformance class (http://www.dgiwg.org/std/csw/1.0/conf/basic)`
 * Requirement 19: `This service implements the DGIWG Catalogue Service for the Web ISO Profile version 1.0, DGIWG Basic CSW conformance class (http://www.dgiwg.org/std/csw/1.0/conf/basic) and DGIWG Transactional CSW (”http://www.dgiwg.org/std/csw/1.0/conf/dgiwg_cswt)
`
Requirement 19 appends `and DGIWG Transactional CSW (”http://www.dgiwg.org/std/csw/1.0/conf/dgiwg_cswt)`. 

The abstract of http://dgiwg.geo-solutions.it/geonetwork/srv/eng/csw?REQUEST=GetCapabilities&SERVICE=CSW is `This is the online TESTBED-14 test catalog provided by GeoSolutions. This service implements the DGIWG Catalogue Service for the Web ISO Profile STD-DP-16-012r1 01 March 2018 19 version 1.0, DGIWG Basic CSW conformance class (http://www.dgiwg.org/std/csw/1.0/conf/basic) and DGIWG Transactional CSW (”http://www.dgiwg.org/std/csw/1.0/conf/dgiwg_cswt). Please check the URI quotes.` This includes the version and date of the specification.

Is the exact string expected from the specification?

**Comment by etj** [comment]
The header text `STD-DP-16-012r1 01 March 2018 19` crept into the declaration.
Please re-run the tests.

**Comment by lgoltz** [comment]
Test is successful now. 
But I assume the `"` before the CSW-T identifier is a typo in the specification.

**Comment by lgoltz** [comment]
> But I assume the " before the CSW-T identifier is a typo in the specification.

Documented in #2
