### ISSUE TITLE
Allow testing of CSW-T with basic authentication 

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-cat20-dgiwg10#29]
see https://github.com/opengeospatial/ets-cat20-dgiwg10/issues/8#issuecomment-422067113

**Comment by lgoltz** [comment]
Related to https://github.com/opengeospatial/teamengine/issues/46 and https://github.com/opengeospatial/ideas/issues/82

**Comment by dstenger** [comment]
#42 solves the issue for now. Further work will be executed in above referenced issues.
