### ISSUE TITLE
Create documentation of test suite

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-cat20-dgiwg10#3]
This includes:
* [x] **site documentation** (all documentation displayed via ```[TEAMENGINE_ENDPOINT]/about/[TEST_SUITE_ID]/[SPEC_VERSION]/site/``` is up to date)
* [x] **REST API documentation** (all documentation displayed via REST API (e.g. ```[TEAMENGINE_ENDPOINT]/rest/suites/```) is up to date)
* [x] **Web Browser Interface documentation** (all content displayed in Web Browser Interface is up to date)

Hints:
* site documentation describes exactly how the tests can be mapped to specification (e.g. abstract test suite described in specification is implemented).
  * This includes a description of the structure of the test suite.
* site documentation references all relevant documents (e.g. specification).

**Comment by lgoltz** [comment]
#42 within docker environment:

```
ENV JAVA_OPTS="-Xms1024m -Xmx2048m -DTE_BASE=/root/te_base -Dtrn.user=USER -Dtrn.pw=PW"
```
