### ISSUE TITLE
Replace currently used record for transactional test with DMF compliant record

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-cat20-dgiwg10#30]
Currently the record from https://www.geoportal.de/gds/xml.php?uuid=C3B4172C-E280-0001-4B22-1B911020BEB0 is used for testing (e.g. https://github.com/opengeospatial/ets-cat20-dgiwg10/blob/master/src/main/resources/org/opengis/cite/cat20/dgiwg10/transaction/insert-DMFMetadata-request.xml)

A DMF compliant record is required.

**Comment by lgoltz** [comment]
@etj Do you know an official DMF compliant example record?

**Comment by etj** [comment]
@lgoltz nope, but we can improve the metadata incrementally as we're testing the various elements

**Comment by etj** [comment]
PR #40 fixes the `metadataStandard*` elements, and that's needed to make GN aware it's a DGIWG record and not a plain 19139 one.

**Comment by lgoltz** [comment]
I close this as no official record is available and the current record is sufficient for the tests.
