### ISSUE TITLE
Transaction/Insert: Bad response from catalog

### ISSUE THREAD

**Issue by etj** [opengeospatial/ets-cat20-dgiwg10#32]
https://github.com/geonetwork/core-geonetwork/issues/3104

**Comment by etj** [comment]
Fix has been implemented on GN 
- master branch: https://github.com/geonetwork/core-geonetwork/pull/3107
- stable branch: https://github.com/geonetwork/core-geonetwork/pull/3108

Fix has already been deployed on test instance.

**Comment by etj** [comment]
Issue will be closed after the PRs have been merged.

**Comment by lgoltz** [comment]
@etj I close this as invalid, as it  is not an issue of the test suite.
