### ISSUE TITLE
Metadata record for Transaction/Insert test is not DGIWG

### ISSUE THREAD

**Issue by etj** [opengeospatial/ets-cat20-dgiwg10#33]
The test record at `src/main/resources/org/opengis/cite/cat20/dgiwg10/transaction/insert-DMFMetadata-request.xml` contains:
```
      <ns4:metadataStandardName>
        <ns2:CharacterString>ISO 19115</ns2:CharacterString>
      </ns4:metadataStandardName>
      <ns4:metadataStandardVersion>
        <ns2:CharacterString>2003/Cor.1:2006</ns2:CharacterString>
      </ns4:metadataStandardVersion>
```
so it's not recognized as a DGIWG metadata record by the catalog. 

The catalog applies different transformations according to the metadata schema.

**Comment by lgoltz** [comment]
Duplicate of #30
