### ISSUE TITLE
Transaction/Insert test does not clean the catalog

### ISSUE THREAD

**Issue by etj** [opengeospatial/ets-cat20-dgiwg10#36]
The Insert test creates a metadata document on the catalog but does not remove it at the end of the test.

This behaviour will make the test fail on subsequent runs, if the record is not deleted manually on the catalog.

**Comment by lgoltz** [comment]
That's correct. The inserted record is removed only if there is no test failure in the following test (update). The inserted record should be removed even if a failure occurred.

**Comment by lgoltz** [comment]
PR: #43
