### ISSUE TITLE
Implement A.1.1 GetCapabilities for DGIWG Basic CSW

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-cat20-dgiwg10#4]
- [x] Issue an HTTP GET capabilities request.
- [x]  Requirement 1 and Requirement 3
- ~~[ ] Requirement 2~~
- [x]  Requirement 4
- [x]  Requirement 6
- [x]  Requirement 5 and Requirement 8 (partly)
- [x]  Requirement 11
- [x]  Requirement 10 (partly)

**Comment by lgoltz** [comment]
Most tests was implemented within commit https://github.com/opengeospatial/ets-cat20-dgiwg10/commit/620a38c9fc09b388a65fdc7adbc3e12ef4243e62

Following tests are missing:
 * Requirement 2: Verify  that  the  response  indicates  support  for  ‘English’  for  queriables  and 
returnables
   * How can we implement this?
 * Requirement 5 and Requirement 8: Verify that the reported queriables and returnables for the GetRecords operation. at least include those defined in section s 7.1.1 and 7.1.3.
   * Requirement 5 is a GetCapabilities test and does not mention GetRecords 
   * Missing references as described in #2, it is assumed that the same queryables and returnables as for Requirement 10 should be supported.
 * Requirement 10: Verify that the reported queriables and returnables for the GetRecordById operation. at least include those defined in sections 7.1.1 and 7.1.3.

**Comment by lgoltz** [comment]
It was decided to test if the Capabilities document contains queryables for GetRecords and GetRecordById operation. It is not specified how the returnables should be declared in the capabilities document as well the queryables defined in CSW 2.0.2 specification. AP ISO specifies in 'Table 23 – Additional GetRecords constraints' two constraints: 
 * SupportedISOQueryables: A list of the supported additional queryables defined in this profile (e.g. parentIdentifier). 
 * AdditionalQueryables A list of add itional queryables defined e.g. by a specific community, not defined in this profile or the base specification. 

Implemented tests: https://github.com/opengeospatial/ets-cat20-dgiwg10/commit/7a042f3df2a32856f43ea5bf7338230f0d994c9d

Furthermore it was decided not to implement Requirement 2.

**Comment by dstenger** [comment]
Add maven-failsafe-plugin: https://github.com/opengeospatial/ets-cat20-dgiwg10/commit/3782433095a1ec91be5398d07073a7ada4f6806a

**Comment by dstenger** [comment]
Update method names of GetCapabilities tests: https://github.com/opengeospatial/ets-cat20-dgiwg10/commit/8e7beb813f8bccf99bc32b46bd885dea9d0f82f8
