### ISSUE TITLE
Improve mechanism to provide record used for harvest operation

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-cat20-dgiwg10#49]
See https://github.com/opengeospatial/ets-cat20-dgiwg10/issues/8#issuecomment-436175976.

**Comment by etj** [comment]
I copied the sample metadata in our dgiwg test server at
   http://dgiwg.geo-solutions.it/test/metadata/DMFMetadataRecord.xml
so that the returned content-type is text/xml, and so it's accepted by gn.

This is a temporary workaround to make the test pass.

**Comment by lgoltz** [comment]
We provided the record at https://opengeospatial.github.io/ets-cat20-dgiwg10/DMFMetadataRecord.xml, the returned content type is application/xml (default of ResourceFormat parameter of the harvest operation). The test issueHarvestRequest fails cause the service returns 

```
<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        version="1.2.0"
        xsi:schemaLocation="http://www.opengis.net/ows http://schemas.opengis.net/ows/1.0.0/owsExceptionReport.xsd">
  <ows:Exception exceptionCode="NoApplicableCode">
      <ows:ExceptionText>Host name 'opengeospatial.github.io' does not match the certificate subject provided by the peer (CN=www.github.com, O="GitHub, Inc.", L=San Francisco, ST=California, C=US)</ows:ExceptionText>
  </ows:Exception>
</ows:ExceptionReport>
```
@etj Can you take a look at this?
