### ISSUE TITLE
Implement A.1.2 GetRecords for DGIWG Basic CSW

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-cat20-dgiwg10#5]
- [x] ~~1. Ensure that the CSW is loaded with metadata which supports all of the queriables and returnables described in table 5, 6, 8, 9 and 10~~
- [x] 2. Issue a number of HTTP POST GetRecords requests with return types of both csw:Record and gmd:MD_Metadata using all of the queriables in Tables 5 and 6.
- [x] 3. Verify that a valid result is obtained (Requirements 6, 7).
- [x] 4. Verify that all metadata returnables are present in the result (Requirement 8)
- [x] ~~5. Verify that the gmd:MD_Metadata record returned is compliant with the DMF specification (Requirement 11) and with ISO19139 (Requirement 12). Returnables shall be mapped to the DMF using tables 5,6,8,9 and 10 (Requirement 8) and additional items in table 9 (Requirement 14).~~ see #14

**Comment by lgoltz** [comment]
Current status: 
> 1. Ensure that the CSW is loaded with metadata which supports all of the queriables and returnables described in table 5, 6, 8, 9 and 10.

Is currently not ensured. 

> 2. Issue a number of HTTP POST GetRecords requests with return types of both csw:Record and gmd:MD_Metadata using all of the queriables in Tables 5 and 6.

Only the queryables Identifier, Title and AnyText are tested. Is this sufficient (for now)? Overall 33 queryabled specified.

> 3. Verify that a valid result is obtained (Requirements 6, 7).

I don't see the relation to Requirement 6 and 7. Currently it is tested if the status code is 200 and the response is schema valid.  

> 4. Verify that all metadata returnables are present in the result (Requirement 8)

I don't see how we can test if the returnables are optional.  

> 5. Verify that the gmd:MD_Metadata record returned is compliant with the DMF specification (Requirement 11) and with ISO19139 (Requirement 12). Returnables shall be mapped to the DMF using tables 5,6,8,9 and 10 (Requirement 8) and additional items in table 9 (Requirement 14).

How can we test this?

**Comment by lgoltz** [comment]
It was decided to skip test method 1.  2. and 3. are sufficient for now. Tests (for all responses from queryable tests) was added to check if the mandatory returnables (see Table 7) are available: 
https://github.com/opengeospatial/ets-cat20-dgiwg10/commit/a4b96254352eb6079d99561f2c453cf499b92d68

5. is discussed in #14
