### ISSUE TITLE
Implement A.1.3 GetRecordById for DGIWG Basic CSW

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-cat20-dgiwg10#6]
- [x] ~~1. Ensure that the CSW is loaded with metadata which supports all of the returnables described in table 5, 6,8,9 and 10.~~
- [x] 2. Issue HTTP POST GetRecordById requests with return types of both csw:Record and gmd:MD_Metadata 
- [x] 3. Verify that a valid result is obtained (Requirement 10).
- [x] 4. Verify that all metadata returnables are present in the result (Requirement 13).
- [x] ~~5. Verify that the gmd:MD_Metadata record returned is compliant with the DMF specification (Requirement 11) and with ISO19139 (Requirement 12). Returnables shall be mapped to the DMF using table 5,6,8,9 and 10 (Requirement 10)~~ see #14

**Comment by lgoltz** [comment]
As decided in #5: Test method 
1. is skipped, 
2. is implemented (https://github.com/opengeospatial/ets-cat20-dgiwg10/commit/b2de2f38d9ffbd8bcfa9325cabea944809777278). 
3. Currently it is tested if the status code is 200 and the response is schema valid.
4. Mandatory Returnable s(see Table 7.) are tested (https://github.com/opengeospatial/ets-cat20-dgiwg10/commit/d6fb2420560b2bcf8fc13fe33d38c07feaeba34a)
5. Discussed in #14
