### ISSUE TITLE
Implement A.1.4 DGIWG Transactional CSW

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-cat20-dgiwg10#7]
- [x] Issue an HTTP GET GetCapabilities Operation. Verify that the Abstract present in the service metadata includes the text defined in requirement 19.
- [x] Issue a HTTP POST CSW INSERT operation with DMF Compliant Metadata. Issue a HTTP POST GetRecords Request to confirm the item was inserted. (Requirement 18)
- [x] Issue a HTTP POST Update Operation with a revised DMF Compliant metadata file.
- [x] Issue a HTTP POST GetRecords Request to confirm the item was updated (Requirement 18).
- [x] Issue a HTTP POST Delete Operation with a revised DMF Compliant metadata file.
- [x] Issue a HTTP POST GetRecords Request to confirm the item was deleted (i.e no records returned). (Requirement 18)

**Comment by lgoltz** [comment]
Branch: https://github.com/opengeospatial/ets-cat20-dgiwg10/tree/implementA_1_4-7

Test methods was implemented. Open tasks:
 * Currently the record from https://www.geoportal.de/gds/xml.php?uuid=C3B4172C-E280-0001-4B22-1B911020BEB0 is used for testing. A DMF compliant record is required. 
 * The assertion of the update transaction is not completed, yet. 
 * The required abstarct text from Requirement 19 contains an `"` which may be a typo (see #24 )

**Comment by lgoltz** [comment]
The service http://dgiwg.geo-solutions.it/geonetwork/srv/eng/csw?REQUEST=GetCapabilities&SERVICE=CSW cannot be used for testing. As far as I see transaction requests requires authentication.
