### ISSUE TITLE
Implement A.1.5 DGIWG Transactional CSW

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-cat20-dgiwg10#8]
- [x] Issue a HTTP POST CSW INSERT operation with DMF Compliant Metadata.
- [x] Issue a HTTP POST GetRecords Request to confirm the item was inserted (Requirement 17).
- [x] Issue a HTTP POST Update Operation with a revised DMF Compliant metadata file.
- [x] Issue a HTTP POST GetRecords Request to confirm the item was updated (Requirement 17)
- [x] Issue a HTTP POST Delete Operation with a revised DMF Compliant metadata file.
- [x] Issue a HTTP POST GetRecords Request to confirm the item was deleted (i.e no records returned) (Requirement 17).
- [x] Issue a HTTP POST Harvest Request and confirm that all records are returned (Requirement 18)

**Comment by lgoltz** [comment]
What are the differences between A.14 and A.1.5 (with the exception of the additional test method for the Harvest operation)? Does A.1.5 handle service metadata records (Requirement 17 handles service records)? 
```
Requirement 17: Implementations of this DGIWG profile shall implement support for
querying using the additional Metadata Items shown in table 10 for Service elements.
```
The relation between A.1.5 and Requirement 17 is not clear.

Testing of the Harvest operation should be limited to a reference to a ISO 19139 metadata document (ResourceType=http://www.isotc211.org/schemas/2005/gmd/). The resource to harvest must be provided by the ets.

**Comment by etj** [comment]
Pls note that GeoNetwork requires basic authentication for performing transactional request.

e.g.:

I created the file `csw-insert.xml` with the content used in the tests (metadata with title "Arbeitslosenquote")

```
$ curl -i -u admin:*********  -XPOST -d @csw-insert.xml -H "Content-type: text/xml"  http://dgiwg.geo-solutions.it/geonetwork/srv/eng/csw-publication
HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Date: Mon, 17 Sep 2018 15:08:39 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips
Set-Cookie: JSESSIONID=E2E67148519A1EE5CB143DDD60E6F847; Path=/geonetwork; HttpOnly
Set-Cookie: serverTime=1537196919555; Path=/
Set-Cookie: sessionExpiry=1537196919555; Path=/
X-Frame-Options: DENY
Content-Security-Policy: frame-ancestors 'none'
Pragma: no-cache
Cache-Control: no-cache
Expires: -1
Content-Type: application/xml;charset=UTF-8
Transfer-Encoding: chunked

<?xml version="1.0" encoding="UTF-8"?>
<csw:TransactionResponse xmlns:csw="http://www.opengis.net/cat/csw/2.0.2">
  <csw:TransactionSummary>
    <csw:totalInserted>1</csw:totalInserted>
    <csw:totalUpdated>0</csw:totalUpdated>
    <csw:totalDeleted>0</csw:totalDeleted>
  </csw:TransactionSummary>
  <csw:InsertResult handleRef="handleRefValue">
    <csw:BriefRecord>
      <identifier>C3B4172C-E280-0001-4B22-1B911020BEB0</identifier>
    </csw:BriefRecord>
  </csw:InsertResult>
</csw:TransactionResponse>
```

I can provide credentials for a user allowed to create/edit metadata.

**Comment by lgoltz** [comment]
@etj I've created a new enhancement for this: #29

**Comment by lgoltz** [comment]
The ATS 1.5 was implemented in the same way as 1.4 but a service record is used instead of a dataset record. The record was taken from https://www.geoportal.de/gds/xml.php?uuid=1a0d46d6-0f93-4564-9e19-de75480e160b and the metadataStandardName and metadataStandardVersion changed to DMF compliant values.

Harvesting was implemented with record https://www.geoportal.de/gds/xml.php?uuid=C3B4183D-1F70-0001-3BFA-AF761F001BF0 and changed metadataStandardName and metadataStandardVersion. The record is currently stored in a gist (https://gist.githubusercontent.com/lgoltz/57f0c19715f47fd9163f20261a2b1342/raw/6642528cc920277f9d731f139ec5a2e137651cb9/DMFMetadataRecord.xml), a better place should be found. Furthermore this must be available from the SUT (documentation must be enhanced). 
There may be problems as the Content-Type is text/plain.

**Comment by lgoltz** [comment]
@etj I've tested with http://dgiwg.geo-solutions.it/geonetwork/srv/eng/csw?REQUEST=GetCapabilities&SERVICE=CSW but harvesting fails with the following exception:
```
<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows"
                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     version="1.2.0"
                     xsi:schemaLocation="http://www.opengis.net/ows http://schemas.opengis.net/ows/1.0.0/owsExceptionReport.xsd">
  <ows:Exception exceptionCode="NoApplicableCode">
      <ows:ExceptionText>org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'CswService.Harvest' is defined</ows:ExceptionText>
  </ows:Exception>
</ows:ExceptionReport>
```

Can you check if this is a failure in the service?

**Comment by etj** [comment]
Checking...

**Comment by dstenger** [comment]
@etj Can you please create a new bug issue if you locate the reason of failure in the test suite?

**Comment by etj** [comment]
The Harvest operation is indeed failing on GeoNetwork side.

Issue opened at  https://github.com/geonetwork/core-geonetwork/issues/3258
